version: '3'
services:

  redis:
    image: 'redis:7.0.0'
    restart: 'always'
    ports:
      - '6379:6379'
    networks:
      - elevate_net
    logging:
      driver: local
    healthcheck:
     test: ["CMD", "redis-cli", "ping"]
     interval: 5s
     timeout: 5s
     retries: 20

  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.3.0'
    ports:
      - '2181:2181'
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - elevate_net
    logging:
      driver: none

  kafka:
    image: 'confluentinc/cp-kafka:7.3.0'
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Listeners configured for CI internal docker networking
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - elevate_net
    healthcheck:
      test: kafka-topics --bootstrap-server localhost:9092 --list || exit 1
      interval: 10s
      timeout: 30s
      retries: 10
    logging:
      driver: local

  citus:
    image: citusdata/citus:13.0
    container_name: citus_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    networks:
      - elevate_net
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  mentoring:
    build: '../' 
    image: elevate/mentoring:2.4
    volumes:
      - ../src/:/var/src
    ports:
      - '3000:3000'
      - '9229:9229'
    command: npm run dev

    environment:
      - KAFKA_URL=kafka:9092
      - USER_SERVICE_HOST=http://user:3001
      - REDIS_HOST=redis://redis:6379
      - SCHEDULER_SERVICE_HOST=http://scheduler:4000
      - DEV_DATABASE_URL=postgres://postgres:postgres@citus:5432/elevate-mentoring
      - ENABLE_CHAT=false
      - ADMIN_SECRET_CODE=ADMIN_SECRET_CODE
    depends_on:
      kafka:
        condition: service_healthy
      citus:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - elevate_net
    env_file:
      - ./integration_test.mentoring.env

  user:
    build: '../../user/' 
    image: elevate/user:2.4
    volumes:
      - ../../user/src/:/var/src
    ports:
      - '3001:3001'
     # - '9229:9229'
    command: >
      sh -c "sleep 20 && 
             npm run db:init && 
             npm run db:seed:all && 
             nodemon --trace-warnings app.js"
    environment:
      - KAFKA_URL=kafka:9092
      - REDIS_HOST=redis://redis:6379
      - SCHEDULER_SERVICE_HOST=http://scheduler:4000
      - DEV_DATABASE_URL=postgres://postgres:postgres@citus:5432/mentoring_user
      - ENABLE_EMAIL_OTP_VERIFICATION=false
      - ADMIN_SECRET_CODE=ADMIN_SECRET_CODE
    depends_on:
      kafka:
        condition: service_healthy
      citus:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - elevate_net
    env_file:
      - ./integration_test.user.env

networks:
  elevate_net:
    external: false

volumes:
  zookeeper-data:
  kafka-data: